"""
Schemas package exports for CareerCrew.
"""

from app.schemas.health import (
    HealthResponse,
    OllamaStatus,
    DatabaseStatus,
    VectorStoreStatus,
    SystemStatusResponse,
    OllamaTestPromptRequest,
    OllamaTestPromptResponse,
)
from app.schemas.ingestion import (
    NormalizedDocument,
    DocumentMetadata,
    IngestionResponse,
)
from app.schemas.entities import (
    ResumeBase,
    ResumeCreate,
    ResumeResponse,
    JobDescriptionBase,
    JobDescriptionCreate,
    JobDescriptionResponse,
    ProjectBase,
    ProjectCreate,
    ProjectResponse,
    ApplicationBase,
    ApplicationCreate,
    ApplicationResponse,
    AnalysisRunBase,
    AnalysisRunCreate,
    AnalysisRunResponse,
)

from app.schemas.intelligence import (
    MatchClassification,
    RequirementType,
    SkillCategory,
    ContactMetadata,
    SkillsInventory,
    EducationItem,
    WorkExperienceItem,
    ProjectItem,
    ResumeProfile,
    CategorizedRequirement,
    JobProfile,
    RequirementMatchResult,
    DimensionScores,
    ProjectRelevanceItem,
    AnalysisMetadata,
    AnalysisResult,
)

from app.schemas.evidence import (
    ConfidenceLevel,
    EvidenceType,
    EvidenceItem,
    ProjectRegisterRequest,
    GitCommitSummary,
    GitMetadata,
    SkillVerificationResult,
    EvidenceChainItem,
    EvidenceAssessment,
)

__all__ = [
    "HealthResponse",
    "OllamaStatus",
    "DatabaseStatus",
    "VectorStoreStatus",
    "SystemStatusResponse",
    "OllamaTestPromptRequest",
    "OllamaTestPromptResponse",
    "NormalizedDocument",
    "DocumentMetadata",
    "IngestionResponse",
    "ResumeBase",
    "ResumeCreate",
    "ResumeResponse",
    "JobDescriptionBase",
    "JobDescriptionCreate",
    "JobDescriptionResponse",
    "ProjectBase",
    "ProjectCreate",
    "ProjectResponse",
    "ApplicationBase",
    "ApplicationCreate",
    "ApplicationResponse",
    "AnalysisRunBase",
    "AnalysisRunCreate",
    "AnalysisRunResponse",
    "MatchClassification",
    "RequirementType",
    "SkillCategory",
    "ContactMetadata",
    "SkillsInventory",
    "EducationItem",
    "WorkExperienceItem",
    "ProjectItem",
    "ResumeProfile",
    "CategorizedRequirement",
    "JobProfile",
    "RequirementMatchResult",
    "DimensionScores",
    "ProjectRelevanceItem",
    "AnalysisMetadata",
    "AnalysisResult",
    "ConfidenceLevel",
    "EvidenceType",
    "EvidenceItem",
    "ProjectRegisterRequest",
    "GitCommitSummary",
    "GitMetadata",
    "SkillVerificationResult",
    "EvidenceChainItem",
    "EvidenceAssessment",
]

